version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9  # Base Docker image for running the pipeline
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker  # Enables Docker inside CircleCI
      - run:
          name: Build Docker image
          command: docker build -t my-docker-image .
      - run:
          name: Run Tests inside Docker
          command: docker run my-docker-image pytest

  deploy:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Tag and Push Docker Image
          command: |
            docker tag my-docker-image mydockerhubusername/my-docker-image:latest
            docker push mydockerhubusername/my-docker-image:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Ensures deploy runs only after build is successful
